let pokemonList= [{name: "", height: "", type:["",""]},
                {name: "", height: "", type:["",""]},
                {name: "", height: "", type:["",""]},
                {name: "", height: "", type:["",""]},
                {name: "", height: "", type:["",""]},
